[providers]
node = {}

[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "dbus",
  "xcb-util",
  "libxkbcommon",
  "libGL",
  "libXcomposite",
  "libXdamage",
  "libXfixes",
  "libXrandr",
  "libgbm",
  "alsa-lib",
  "pango",
  "cairo"
]

[env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NIXPACKS_ALLOW_UNFREE = "1"